### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by trixr4kdz** [Tohoma/yah#14]
I feel like we have way too many branches now that we don't really need. I think it's time that we just make a branch for a specific functionality and not for specific people. Because it doesn't really make sense if more than 1 person works on the same function at the same time; this will most definitely produce a lot of merge conflicts. So here's what I propose:
* Delete all the branches that have been merged already (I already deleted my "trixie" branch), or you don't really use/need; only make a new one if you want to work on a specific thing without being bothered by the other members
* Rename branches based on their functionality (i.e., PC-Scanner should just be scanner, etc.)
* Since master has been moving, all of the remaining branches are falling behind. We have to make sure to merge master into them so they are caught up. Once that is done, we can start fresh again.

**Note: The key thing here is that master SHOULD NOT be ahead of the sub-branches. The point of branching out is to collect them all into master once the members are satisfied with the changes in those branches.

**Comment by rtoal** [comment]
Agreed that branches should be deleted after merging for sure. It's okay to have a handful open, though, even on a small team.

Initialed branches are fine though. Here's why people like them: https://www.viget.com/articles/git-tips. Of course they are not universally used. Up to you if you want to use them or not.

And by all means keep your branches up-to-date with master!

**Comment by Tohoma** [comment]
This is still an issue please read.

**Comment by trixr4kdz** [comment]
I will give $2 to the team member who reads this message (besides Peyton and Dr. Toal).

**Comment by cjdellomes** [comment]
Nice. Free money. Also, I'll see if I can delete those branches.

**Comment by Tohoma** [comment]
Whomp
