### ISSUE TITLE
Multiline Comments

### ISSUE THREAD

**Issue by Tohoma** [Tohoma/yah#6]
Are we attached to /// /// being multiline? I still kinda like the previous //\ \\/. I feel like it sticks out more, and it gives our language a bit of flavor.

**Comment by adrianlu95** [comment]
I'm looking over this and editing, and either way we decide to go, I don't personally care, but currently, the ReadMe is incorrect in its description of our comments.

**Comment by adrianlu95** [comment]
On a somewhat unrelated note, I'm not sure how much I love our current method of setting things to NaN, undefined, and nil. I don't like the idea of using characters that aren't readily accessible on a keyboard.

**Comment by adrianlu95** [comment]
and one more thing, is our language called Yah or Yahscript? Our logo says Yah, as does our repo, but all throughout we are calling it Yahscript.

**Comment by Tohoma** [comment]
It's renamed to yah we have to edit the Readme

**Comment by VicFrolov** [comment]
I'm okay with both forms of comments //\  \\/ is pretty cool actually

**Comment by trixr4kdz** [comment]
I vote for the //\ \\/ comment.

Makes us unique XP. You guys vote here too so we can close this issue

**Comment by Tohoma** [comment]
I vote for //\ \\/.

**Comment by VicFrolov** [comment]
I'll vote for  //\ \\/ over //\ \/ since the former has a pattern

**Comment by Tohoma** [comment]
I choose ///.
